from api.controller.students_controller import student_api
from api.controller.auth_controller import student_auth_api
from api.controller.courses_controller import course_api
from api.controller.lecturers_controller import lecturer_api