"""Add reg_complete column to Student model

Revision ID: 0836860af27d
Revises: c4b290814f08
Create Date: 2019-08-08 12:07:50.558633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0836860af27d'
down_revision = 'c4b290814f08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('reg_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'reg_complete')
    # ### end Alembic commands ###
