"""update cloumn has_registered_courses to has_registered_course

Revision ID: 085dfd884e1d
Revises: b0c9317da81a
Create Date: 2019-08-23 16:28:34.379298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '085dfd884e1d'
down_revision = 'b0c9317da81a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('has_registered_course', sa.Boolean(), nullable=True))
    op.drop_column('students', 'has_registered_courses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('has_registered_courses', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('students', 'has_registered_course')
    # ### end Alembic commands ###
