"""Add has_assigned_courses to hod table

Revision ID: 3e4649d3af3d
Revises: 085dfd884e1d
Create Date: 2019-08-24 12:46:19.631062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4649d3af3d'
down_revision = '085dfd884e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hods', sa.Column('has_assigned_courses', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hods', 'has_assigned_courses')
    # ### end Alembic commands ###
