"""Create assign courses table second_18

Revision ID: 52ef2c763c9d
Revises: 1ec6f953b614
Create Date: 2019-08-22 02:07:28.870448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52ef2c763c9d'
down_revision = '1ec6f953b614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assgined_courses_second_2018_2019',
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.id'], ),
    sa.PrimaryKeyConstraint('lecturer_id', 'course_id')
    )
    op.drop_table('assgined_courses_second_2018_2018')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assgined_courses_second_2018_2018',
    sa.Column('lecturer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='assgined_courses_second_2018_2018_ibfk_1'),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.id'], name='assgined_courses_second_2018_2018_ibfk_2'),
    sa.PrimaryKeyConstraint('lecturer_id', 'course_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('assgined_courses_second_2018_2019')
    # ### end Alembic commands ###
