"""Change fingerprint table name

Revision ID: 5d948e7cfff4
Revises: 0205bd762564
Create Date: 2019-09-19 20:19:13.426355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d948e7cfff4'
down_revision = '0205bd762564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('fingerprint_template', sa.String(length=1112), nullable=True))
    op.drop_index('fingerprint', table_name='students')
    op.create_unique_constraint(None, 'students', ['fingerprint_template'])
    op.drop_column('students', 'fingerprint')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('fingerprint', mysql.VARCHAR(length=1112), nullable=True))
    op.drop_constraint(None, 'students', type_='unique')
    op.create_index('fingerprint', 'students', ['fingerprint'], unique=True)
    op.drop_column('students', 'fingerprint_template')
    # ### end Alembic commands ###
