"""create registered courses second 18

Revision ID: b0c9317da81a
Revises: 52ef2c763c9d
Create Date: 2019-08-23 15:20:59.747925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c9317da81a'
down_revision = '52ef2c763c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registered_courses_second_2018_2019',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    op.add_column('students', sa.Column('has_registered_courses', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'has_registered_courses')
    op.drop_table('registered_courses_second_2018_2019')
    # ### end Alembic commands ###
