from api.model.semesters_model import Semester
from api.model.levels_model import Level
from api.model.schools_model import School
from api.model.students_model import Student
from api.model.departments_model import Department
from api.model.courses_model import Course
from api.model.lecturers_model import Lecturer
from api.model.hod_model import HOD
from api.model.revoked_token_model import RevokedToken
